[package]
name = "flatterer-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "0.16.0"
async-std = { version = "1.10.0", features = ["attributes", "unstable"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
libflatterer = { version = "0.7" }
tempfile = "3"
surf = "2.3"
zip = "0.5"
walkdir = "2"
env_logger = "0.9"
uuid = { version = "0.8", features = ["serde", "v4"] }
